apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: bestrongacr.azurecr.io/my-fluentd:custom
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch" # Ім'я сервісу Elasticsearch
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200" # Порт Elasticsearch
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http" # Для локального використання HTTPS не потрібен
        - name: FLUENT_UID
          value: "0"
        # resources:
        #   limits:
        #     memory: 500Mi # Збільшено з 200Mi
        #   requests:
        #     cpu: 200m # Збільшено з 100m
        #     memory: 300Mi # Збільшено з 200Mi
        volumeMounts:
        - name: default-config-volume
          mountPath: /fluentd/etc/kubernetes.conf
          subPath: kubernetes.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: default-config-volume
        configMap:
          name: fluentd-conf
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
