apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: myapp-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: MyAppAlerts
      rules:
        - alert: HighCPUUsage
          expr: (sum(rate(container_cpu_usage_seconds_total{pod=~"myapp-.*"}[1m])) * 1000 / 250 * 100) > 70
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage for myapp containers"
            description: "The CPU usage for myapp containers is above 70% for more than 2 minutes. Current value: {{ $value }}%"
        - alert: HighMemoryUsage
          expr: (100 * sum(container_memory_working_set_bytes{pod=~"myapp-.*"}) / sum(machine_memory_bytes)) > 70
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage for myapp containers"
            description: "The memory usage for myapp containers is above 70% for more than 2 minutes. Current value: {{ $value }}%"
