apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: myapp-cpu-alert
  namespace: monitoring
spec:
  groups:
  - name: myapp-cpu-alerts
    rules:
    - alert: MyAppHighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{pod=~"myapp.*"}[2m])) / sum(kube_pod_container_resource_limits_cpu_cores{pod=~"myapp.*"}) > 0.7
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected in MyApp pods"
        description: "One or more MyApp pods are using more than 70% of their CPU limits for over 1 minute."
