apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: myapp-alert-rules
  namespace: monitoring
spec:
  groups:
  - name: myapp-alerts
    rules:
    - alert: MyAppHighMemoryUsage
      expr: sum(container_memory_usage_bytes{pod=~"myapp*"}) / sum(container_memory_working_set_bytes{pod=~"myapp*"}) > 0.7
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage detected in MyApp pods"
        description: "Memory usage in one or more myapp pods exceeded 70% for 1 minute."

    - alert: MyAppHighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{pod=~"myapp*"}[2m])) / sum(container_cpu_quota{pod=~"myapp*"}) > 0.7
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected in MyApp pods"
        description: "CPU usage in one or more myapp pods exceeded 70% for 1 minute."
