apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stable
  labels:
    app: {{ .Chart.Name }}
    version: stable
spec:
  replicas: {{ .Values.replicaCount.stable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: stable
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: stable
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.stable.repository }}:{{ .Values.image.stable.tag }}"
        imagePullPolicy: {{ .Values.image.stable.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      nodeSelector: {{ .Values.nodeSelector | toJson }}
      tolerations: {{ .Values.tolerations | toJson }}
      affinity: {{ .Values.affinity | toJson }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-canary
  labels:
    app: {{ .Chart.Name }}
    version: canary
spec:
  replicas: {{ .Values.replicaCount.canary }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: canary
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: canary
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.canary.repository }}:{{ .Values.image.canary.tag }}"
        imagePullPolicy: {{ .Values.image.canary.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      nodeSelector: {{ .Values.nodeSelector | toJson }}
      tolerations: {{ .Values.tolerations | toJson }}
      affinity: {{ .Values.affinity | toJson }}
