variables:
- group: helm-pipeline


stages:
- stage: Build_And_Push_Helm
  displayName: "Build and Push Helm Charts to ACR"
  jobs:
  - job: PackAndPushHelm
    displayName: "Pack and Push Helm Charts to ACR"
    steps:
    - task: HelmInstaller@1
      displayName: "Install Helm"
      inputs:
        helmVersion: 'latest'

    - script: |
        helm lint ./helm
        helm package ./helm --destination ./artifacts
      displayName: "Lint and Pack Helm Charts"

    - task: AzureCLI@2
      displayName: "Login to Azure and push actifact"
      inputs:
        azureSubscription: "lnu_sub"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR)
          az acr helm push --name $(ACR) ./artifacts/*

    

- stage: Deploy_to_AKS
  displayName: "Deploy to AKS"
  dependsOn: Build_And_Push_Helm
  jobs:
  - job: Deploy
    displayName: "Deploy to AKS"
    steps:
    - task: AzureCLI@2
      displayName: "Login to Azure"
      inputs:
        azureSubscription: "lnu_sub"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group $(resource-group) --name $(aks-cluster)

    - script: |
        helm repo add helmrepo https://$(ACR).azurecr.io/helm/v1/repo
        helm repo update
        helm upgrade --install bestrong helmrepo --namespace default
      displayName: "Deploy Helm Chart to AKS"
