variables:
- group: helm-pipeline


stages:
- stage: Build_And_Push_Helm
  displayName: "Build and Push Helm Charts to ACR"
  jobs:
  - job: PackAndPushHelm
    displayName: "Pack and Push Helm Charts to ACR"
    steps:
    - task: HelmInstaller@1
      displayName: "Install Helm"
      inputs:
        helmVersion: 'latest'
    - script: |
        VERSION=$(grep '^version:' ./helm/Chart.yaml | awk '{print $2}')

        # Формуємо змінну, яка включає Build.BuildId
        FULL_VERSION="${VERSION}.${Build.BuildId}"

        # Виводимо результат
        echo "Full Version: $FULL_VERSION"
      displayName: "Extract and Set Helm Chart Version"

    - script: |
        helm lint ./helm
        helm package ./helm --version $(Build.BuildId)" --destination ./artifacts
      displayName: "Lint and Pack Helm Charts"

    - task: AzureCLI@2
      displayName: "Login to Azure and push actifact"
      inputs:
        azureSubscription: "lnu_sub"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR)
          export HELM_EXPERIMENTAL_OCI=1
          helm push ./artifacts/myapp-$(Build.BuildId).tgz oci://$(ACR).azurecr.io/helmrepo

    

- stage: Deploy_to_AKS
  displayName: "Deploy to AKS"
  dependsOn: Build_And_Push_Helm
  jobs:
  - job: Deploy
    displayName: "Deploy to AKS"
    steps:
    - task: AzureCLI@2
      displayName: "Login to Azure"
      inputs:
        azureSubscription: "lnu_sub"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group $(resource-group) --name $(aks-cluster)
          az acr login --name $(ACR)
          export HELM_EXPERIMENTAL_OCI=1
          helm pull oci://$(ACR).azurecr.io/helmrepo/myapp --version $(Build.BuildId)
          helm upgrade --install myapp myapp-$(Build.BuildId).tgz

