apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bestrong-api-cert
  namespace: default
spec:
  secretName: bestrong-api-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: bestronger.pp.ua
  dnsNames:
  - bestronger.pp.ua
